CHAT_MODEL_TABLE = {
    "google/gemma-7b": Model(
        id = "google/gemma-7b",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-gemma-7b", "playground_gemma_7b", "gemma_7b"],
        deprecated = True,
    ),
    "mistralai/mistral-7b-instruct-v0.2": Model(
        id = "mistralai/mistral-7b-instruct-v0.2",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-mistral-7b-instruct-v2", "playground_mistral_7b", "mistral_7b"],
        deprecated = True,
    ),
    "mistralai/mixtral-8x7b-instruct-v0.1": Model(
        id = "mistralai/mixtral-8x7b-instruct-v0.1",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-mixtral-8x7b-instruct", "playground_mixtral_8x7b", "mixtral_8x7b"],
    ),
    "google/codegemma-7b": Model(
        id = "google/codegemma-7b",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-codegemma-7b"],
    ),
    "gotocompany/gemma-2-9b-cpt-sahabatai-instruct": Model(
        id = "gotocompany/gemma-2-9b-cpt-sahabatai-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "mistralai/mixtral-8x22b-instruct-v0.1": Model(
        id = "mistralai/mixtral-8x22b-instruct-v0.1",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-mixtral-8x22b-instruct"],
    ),
    "mistralai/mixtral-8x22b-v0.1": Model(
        id = "mistralai/mixtral-8x22b-v0.1",
        model_type = "chat",
        client = "ChatNVIDIA",
    ),
    "meta/llama3-8b-instruct": Model(
        id = "meta/llama3-8b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-llama3-8b"],
        deprecated = True,
    ),
    "meta/llama3-70b-instruct": Model(
        id = "meta/llama3-70b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-llama3-70b"],
        deprecated = True,
    ),
    "microsoft/phi-3-mini-128k-instruct": Model(
        id = "microsoft/phi-3-mini-128k-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-phi-3-mini"],
        deprecated = True,
    ),
    "microsoft/phi-3-mini-4k-instruct": Model(
        id = "microsoft/phi-3-mini-4k-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-phi-3-mini-4k", "playground_phi2", "phi2"],
        deprecated = True,
    ),
    "aisingapore/sea-lion-7b-instruct": Model(
        id = "aisingapore/sea-lion-7b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-sea-lion-7b-instruct"],
        deprecated = True,
    ),
    "microsoft/phi-3-small-8k-instruct": Model(
        id = "microsoft/phi-3-small-8k-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-phi-3-small-8k-instruct"],
        deprecated = True,
    ),
    "microsoft/phi-3-small-128k-instruct": Model(
        id = "microsoft/phi-3-small-128k-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-phi-3-small-128k-instruct"],
        deprecated = True,
    ),
    "microsoft/phi-3-medium-4k-instruct": Model(
        id = "microsoft/phi-3-medium-4k-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-phi-3-medium-4k-instruct"],
        deprecated = True,
    ),
    "ibm/granite-3.3-8b-instruct": Model(
        id = "ibm/granite-3.3-8b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_thinking = True,
        supports_tools = True,
        thinking_param_enable = { "chat_template_kwargs": { "enable_thinking": True } },
        thinking_param_disable = { "chat_template_kwargs": { "enable_thinking": False } },
        deprecated = True,
    ),
    "ibm/granite-guardian-3.0-8b": Model(
        id = "ibm/granite-guardian-3.0-8b",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "mediatek/breeze-7b-instruct": Model(
        id = "mediatek/breeze-7b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-breeze-7b-instruct"],
        deprecated = True,
    ),
    "upstage/solar-10.7b-instruct": Model(
        id = "upstage/solar-10.7b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-solar-10_7b-instruct"],
    ),
    "mistralai/mistral-7b-instruct-v0.3": Model(
        id = "mistralai/mistral-7b-instruct-v0.3",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-mistral-7b-instruct-v03"],
    ),
    "01-ai/yi-large": Model(
        id = "01-ai/yi-large",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-yi-large"],
    ),
    "mistralai/codestral-22b-instruct-v0.1": Model(
        id = "mistralai/codestral-22b-instruct-v0.1",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-codestral-22b-instruct-v01"],
        supports_structured_output = True,
    ),
    "google/gemma-2-9b-it": Model(
        id = "google/gemma-2-9b-it",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-gemma-2-9b-it"],
        deprecated = True,
    ),
    "google/gemma-2-27b-it": Model(
        id = "google/gemma-2-27b-it",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-gemma-2-27b-it"],
        deprecated = True,
    ),
    "google/gemma-3-12b-it": Model(
        id = "google/gemma-3-12b-it",
        model_type = "chat",
        client = "ChatNVIDIA",
    ),
    "google/gemma-3-1b-it": Model(
        id = "google/gemma-3-1b-it",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "google/gemma-3-27b-it": Model(
        id = "google/gemma-3-27b-it",
        model_type = "chat",
        client = "ChatNVIDIA",
    ),
    "google/gemma-3-4b-it": Model(
        id = "google/gemma-3-4b-it",
        model_type = "chat",
        client = "ChatNVIDIA",
    ),
    "google/gemma-3n-e2b-it": Model(
        id = "google/gemma-3n-e2b-it",
        model_type = "vlm",
        client = "ChatNVIDIA",
    ),
    "google/gemma-3n-e4b-it": Model(
        id = "google/gemma-3n-e4b-it",
        model_type = "vlm",
        client = "ChatNVIDIA",
    ),
    "google/shieldgemma-9b": Model(
        id = "google/shieldgemma-9b",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "microsoft/phi-3-medium-128k-instruct": Model(
        id = "microsoft/phi-3-medium-128k-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        aliases = ["ai-phi-3-medium-128k-instruct"],
        deprecated = True,
    ),
    "nv-mistralai/mistral-nemo-12b-instruct": Model(
        id = "nv-mistralai/mistral-nemo-12b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
        deprecated = True,
    ),
    "meta/llama-3.1-8b-instruct": Model(
        id = "meta/llama-3.1-8b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
    ),
    "meta/llama-3.1-70b-instruct": Model(
        id = "meta/llama-3.1-70b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
    ),
    "meta/llama-3.1-405b-instruct": Model(
        id = "meta/llama-3.1-405b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
        deprecated = True,
    ),
    "meta/llama-guard-4-12b": Model(
        id = "meta/llama-guard-4-12b",
        model_type = "chat",
        client = "ChatNVIDIA",
    ),
    "mistralai/mamba-codestral-7b-v0.1": Model(
        id = "mistralai/mamba-codestral-7b-v0.1",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "google/gemma-2-2b-it": Model(
        id = "google/gemma-2-2b-it",
        model_type = "chat",
        client = "ChatNVIDIA",
    ),
    "mistralai/magistral-small-2506": Model(
        id = "mistralai/magistral-small-2506",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "mistralai/mistral-medium-3-instruct": Model(
        id = "mistralai/mistral-medium-3-instruct",
        model_type = "vlm",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "mistralai/mistral-nemotron": Model(
        id = "mistralai/mistral-nemotron",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
    ),
    "mistralai/mistral-small-24b-instruct": Model(
        id = "mistralai/mistral-small-24b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "mistralai/mistral-small-3.1-24b-instruct-2503": Model(
        id = "mistralai/mistral-small-3.1-24b-instruct-2503",
        model_type = "vlm",
        client = "ChatNVIDIA",
        supports_tools = True,
        deprecated = True,
    ),
    "mistralai/mathstral-7b-v0.1": Model(
        id = "mistralai/mathstral-7b-v0.1",
        model_type = "chat",
        client = "ChatNVIDIA",
    ),
    "rakuten/rakutenai-7b-instruct": Model(
        id = "rakuten/rakutenai-7b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "rakuten/rakutenai-7b-chat": Model(
        id = "rakuten/rakutenai-7b-chat",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "baichuan-inc/baichuan2-13b-chat": Model(
        id = "baichuan-inc/baichuan2-13b-chat",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "thudm/chatglm3-6b": Model(
        id = "thudm/chatglm3-6b",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "tiiuae/falcon3-7b-instruct": Model(
        id = "tiiuae/falcon3-7b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "microsoft/phi-3.5-mini-instruct": Model(
        id = "microsoft/phi-3.5-mini-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "microsoft/phi-4-mini-flash-reasoning": Model(
        id = "microsoft/phi-4-mini-flash-reasoning",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "microsoft/phi-4-mini-instruct": Model(
        id = "microsoft/phi-4-mini-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
    ),
    "microsoft/phi-4-multimodal-instruct": Model(
        id = "microsoft/phi-4-multimodal-instruct",
        model_type = "vlm",
        client = "ChatNVIDIA",
    ),
    "utter-project/eurollm-9b-instruct": Model(
        id = "utter-project/eurollm-9b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "nvidia/nemotron-mini-4b-instruct": Model(
        id = "nvidia/nemotron-mini-4b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
    ),
    "yentinglin/llama-3-taiwan-70b-instruct": Model(
        id = "yentinglin/llama-3-taiwan-70b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "tokyotech-llm/llama-3-swallow-70b-instruct-v0.1": Model(
        id = "tokyotech-llm/llama-3-swallow-70b-instruct-v0.1",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "abacusai/dracarys-llama-3.1-70b-instruct": Model(
        id = "abacusai/dracarys-llama-3.1-70b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
    ),
    "qwen/qwen2-7b-instruct": Model(
        id = "qwen/qwen2-7b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "meta/llama-3.2-1b-instruct": Model(
        id = "meta/llama-3.2-1b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
    ),
    "meta/llama-3.2-3b-instruct": Model(
        id = "meta/llama-3.2-3b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
    ),
    "institute-of-science-tokyo/llama-3.1-swallow-8b-instruct-v0.1": Model(
        id = "institute-of-science-tokyo/llama-3.1-swallow-8b-instruct-v0.1",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_structured_output = True,
        deprecated = True,
    ),
    "institute-of-science-tokyo/llama-3.1-swallow-70b-instruct-v0.1": Model(
        id = "institute-of-science-tokyo/llama-3.1-swallow-70b-instruct-v0.1",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_structured_output = True,
        deprecated = True,
    ),
    "igenius/colosseum_355b_instruct_16k": Model(
        id = "igenius/colosseum_355b_instruct_16k",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "igenius/italia_10b_instruct_16k": Model(
        id = "igenius/italia_10b_instruct_16k",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "zyphra/zamba2-7b-instruct": Model(
        id = "zyphra/zamba2-7b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
    ),
    "nvidia/nemotron-4-mini-hindi-4b-instruct": Model(
        id = "nvidia/nemotron-4-mini-hindi-4b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_structured_output = True,
        deprecated = True,
    ),
    "nvidia/llama-3.1-nemoguard-8b-content-safety": Model(
        id = "nvidia/llama-3.1-nemoguard-8b-content-safety",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_structured_output = True,
    ),
    "nvidia/llama-3.1-nemoguard-8b-topic-control": Model(
        id = "nvidia/llama-3.1-nemoguard-8b-topic-control",
        model_type = "chat",
        client = "ChatNVIDIA",
    ),
    "nvidia/usdcode-llama-3.1-70b-instruct": Model(
        id = "nvidia/usdcode-llama-3.1-70b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
    ),
    "meta/llama-3.3-70b-instruct": Model(
        id = "meta/llama-3.3-70b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
    ),
    "qwen/qwen2.5-coder-32b-instruct": Model(
        id = "qwen/qwen2.5-coder-32b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
    ),
    "qwen/qwen2.5-coder-7b-instruct": Model(
        id = "qwen/qwen2.5-coder-7b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "qwen/qwen2.5-7b-instruct": Model(
        id = "qwen/qwen2.5-7b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "qwen/qwen3-235b-a22b": Model(
        id = "qwen/qwen3-235b-a22b",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_thinking = True,
        supports_tools = True,
        thinking_param_enable = { "chat_template_kwargs": { "enable_thinking": True } },
        thinking_param_disable = { "chat_template_kwargs": { "enable_thinking": False } },
        deprecated = True,
    ),
    "qwen/qwq-32b": Model(
        id = "qwen/qwq-32b",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        deprecated = True,
    ),
    "nvidia/llama-3.1-nemotron-70b-reward": Model(
        id = "nvidia/llama-3.1-nemotron-70b-reward",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "deepseek-ai/deepseek-r1": Model(
        id = "deepseek-ai/deepseek-r1",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "deepseek-ai/deepseek-r1-0528": Model(
        id = "deepseek-ai/deepseek-r1-0528",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        deprecated = True,
    ),
    "deepseek-ai/deepseek-r1-distill-llama-8b": Model(
        id = "deepseek-ai/deepseek-r1-distill-llama-8b",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "deepseek-ai/deepseek-r1-distill-qwen-14b": Model(
        id = "deepseek-ai/deepseek-r1-distill-qwen-14b",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "deepseek-ai/deepseek-r1-distill-qwen-32b": Model(
        id = "deepseek-ai/deepseek-r1-distill-qwen-32b",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "deepseek-ai/deepseek-r1-distill-qwen-7b": Model(
        id = "deepseek-ai/deepseek-r1-distill-qwen-7b",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "nvidia/llama-3.1-nemotron-nano-8b-v1": Model(
        id = "nvidia/llama-3.1-nemotron-nano-8b-v1",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_thinking = True,
        thinking_prefix = "detailed thinking on",
        no_thinking_prefix = "detailed thinking off",
    ),
    "nvidia/llama-3.1-nemotron-nano-4b-v1.1": Model(
        id = "nvidia/llama-3.1-nemotron-nano-4b-v1.1",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_thinking = True,
        thinking_prefix = "detailed thinking on",
        no_thinking_prefix = "detailed thinking off",
        supports_tools = True,
        deprecated = True,
    ),
    "nvidia/llama-3.1-nemotron-ultra-253b-v1": Model(
        id = "nvidia/llama-3.1-nemotron-ultra-253b-v1",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_thinking = True,
        thinking_prefix = "detailed thinking on",
        no_thinking_prefix = "detailed thinking off",
        supports_tools = True,
        deprecated = True,
    ),
    "nvidia/llama-3.3-nemotron-super-49b-v1": Model(
        id = "nvidia/llama-3.3-nemotron-super-49b-v1",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_thinking = True,
        thinking_prefix = "detailed thinking on",
        no_thinking_prefix = "detailed thinking off",
        supports_tools = True,
        supports_structured_output = True,
    ),
    "nvidia/llama-3.3-nemotron-super-49b-v1.5": Model(
        id = "nvidia/llama-3.3-nemotron-super-49b-v1.5",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_thinking = True,
        thinking_prefix = "/think",
        no_thinking_prefix = "/no_think",
        supports_tools = True,
        supports_structured_output = True,
    ),
    "moonshotai/kimi-k2-instruct": Model(
        id = "moonshotai/kimi-k2-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
    ),
    "openai/gpt-oss-20b": Model(
        id = "openai/gpt-oss-20b",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
    ),
    "openai/gpt-oss-120b": Model(
        id = "openai/gpt-oss-120b",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
    ),
    "marin/marin-8b-instruct": Model(
        id = "marin/marin-8b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "speakleash/bielik-11b-v2.3-instruct": Model(
        id = "speakleash/bielik-11b-v2.3-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        deprecated = True,
    ),
    "nvidia/nvidia-nemotron-nano-9b-v2": Model(
        id = "nvidia/nvidia-nemotron-nano-9b-v2",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
        supports_thinking = True,
        thinking_prefix = "/think",
        no_thinking_prefix = "/no_think",
    ),
    "deepseek-ai/deepseek-v3.1": Model(
        id = "deepseek-ai/deepseek-v3.1",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_thinking = True,
        thinking_param_enable = { "chat_template_kwargs": { "enable_thinking": True } },
        thinking_param_disable = { "chat_template_kwargs": { "enable_thinking": False } },
        deprecated = True,
    ),
    "bytedance/seed-oss-36b-instruct": Model(
        id = "bytedance/seed-oss-36b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
    ),
    "moonshotai/kimi-k2-instruct-0905": Model(
        id = "moonshotai/kimi-k2-instruct-0905",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
    ),
    "qwen/qwen3-next-80b-a3b-instruct": Model(
        id = "qwen/qwen3-next-80b-a3b-instruct",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
    ),
    "qwen/qwen3-next-80b-a3b-thinking": Model(
        id = "qwen/qwen3-next-80b-a3b-thinking",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
    ),
    "deepseek-ai/deepseek-v3.1-terminus": Model(
        id = "deepseek-ai/deepseek-v3.1-terminus",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
        supports_thinking = True,
        thinking_param_enable = { "chat_template_kwargs": { "enable_thinking": True } },
        thinking_param_disable = { "chat_template_kwargs": { "enable_thinking": False } },
    ),
    "minimaxai/minimax-m2": Model(
        id = "minimaxai/minimax-m2",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
        deprecated = True,
    ),
    "moonshotai/kimi-k2-thinking": Model(
        id = "moonshotai/kimi-k2-thinking",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
    ),
    "nvidia/nemotron-3-nano-30b-a3b": Model(
        id = "nvidia/nemotron-3-nano-30b-a3b",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
        supports_thinking = True,
        thinking_param_enable = { "chat_template_kwargs": { "enable_thinking": True } },
        thinking_param_disable = { "chat_template_kwargs": { "enable_thinking": False } },
    ),
    "deepseek-ai/deepseek-v3.2": Model(
        id = "deepseek-ai/deepseek-v3.2",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_thinking = True,
        supports_structured_output = True,
        supports_tools = True,
        thinking_param_enable = { "chat_template_kwargs": { "enable_thinking": True } },
        thinking_param_disable = { "chat_template_kwargs": { "enable_thinking": False } },
    ),
    "stepfun-ai/step-3.5-flash": Model(
        id = "stepfun-ai/step-3.5-flash",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_structured_output = True,
        supports_tools = True,
    ),
    "nvidia/nemotron-3-super-120b-a12b": Model(
        id = "nvidia/nemotron-3-super-120b-a12b",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
        supports_thinking = True,
        thinking_param_enable = { "chat_template_kwargs": { "enable_thinking": True } },
        thinking_param_disable = { "chat_template_kwargs": { "enable_thinking": False } },
    ),
    "minimaxai/minimax-m2.5": Model(
        id = "minimaxai/minimax-m2.5", model_type = "chat", client = "ChatNVIDIA"
    ),
    "google/gemma-4-31b-it": Model(
        id = "google/gemma-4-31b-it",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_thinking = True,
        thinking_param_enable = { "chat_template_kwargs": { "enable_thinking": True } },
        thinking_param_disable = { "chat_template_kwargs": { "enable_thinking": False } },
    ),
    "minimaxai/minimax-m2.7": Model(
        id = "minimaxai/minimax-m2.7",
        model_type = "chat",
        client = "ChatNVIDIA",
    ),
    "z-ai/glm4.7": Model(
        id = "z-ai/glm4.7",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_thinking = True,
        thinking_param_enable = { "chat_template_kwargs": { "enable_thinking": True } },
        thinking_param_disable = { "chat_template_kwargs": { "enable_thinking": False } },
        deprecated = True,
    ),
    "z-ai/glm5": Model(
        id = "z-ai/glm5",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_thinking = True,
        thinking_param_enable = { "chat_template_kwargs": { "enable_thinking": True } },
        thinking_param_disable = { "chat_template_kwargs": { "enable_thinking": False } },
        deprecated = True,
    ),
    "z-ai/glm-5.1": Model(
        id = "z-ai/glm-5.1",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_thinking = True,
        thinking_param_enable = { "chat_template_kwargs": { "enable_thinking": True } },
        thinking_param_disable = { "chat_template_kwargs": { "enable_thinking": False } },
    ),
    "deepseek-ai/deepseek-v4-pro": Model(
        id = "deepseek-ai/deepseek-v4-pro",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
        supports_thinking = True,
        thinking_param_enable = { "chat_template_kwargs": { "thinking": True } },
        thinking_param_disable = { "chat_template_kwargs": { "thinking": False } },
    ),
    "deepseek-ai/deepseek-v4-flash": Model(
        id = "deepseek-ai/deepseek-v4-flash",
        model_type = "chat",
        client = "ChatNVIDIA",
        supports_tools = True,
        supports_structured_output = True,
        supports_thinking = True,
        thinking_param_enable = { "chat_template_kwargs": { "thinking": True } },
        thinking_param_disable = { "chat_template_kwargs": { "thinking": False } },
    ),
}
